Models:
  name: RetinaNet
Backbones:
  name: resnet
  depth: 50
Head:
  name: baseline # senet, sknet, atdh baseline
Data:
  name: bowfiredataset
  root: '/data/4_BoWFireDataset'
  size: 360
Optimize:
  epoch: 500
  display_iter: 100
  display_eval: 49
  lr: 0.001
  optim: 'adam'
  batch_size: 8
  scheduler: 'MultiStepLR'
  lr_step: [ 500 ]
  warmup_steps: 1
  step: 200
  gamma: 0.5

  #  0.1   0.01
  # 500 [ 300, 500 ] 'sgd' 'MultiStepLR' lr:0.1
  # 0.001
  # 500 [ 500 ]  'adam' 'MultiStepLR' lr:0.001
