Models:
  name: RetinaNet
Backbones:
  name: resnet
  depth: 50
Head:
  name: baseline # senet, sknet, atdh, baseline
Data:
  name: minimyfire
  root: '/data/FireDataset'
  size: 608 # remember augmentation need review
Optimize:
  epoch: 1000
  display_iter: 100
  display_eval: 4
  lr: 0.0005
  optim: 'adagrad'
  batch_size: 8
  scheduler: 'MultiStepLR'
  lr_step: [ 500, 1000 ]
  warmup_steps: 1
  step: 200
  gamma: 0.5

  #       0.01 0.005
  # 500 [ 250, 500 ]  'asgd'  'MultiStepLR'  lr:0.01
  # without atdh
  #      0.001 0.0005 0.00025
  # 700 [ 300, 600, 700 ] 'adam' 'MultiStepLR'  lr:0.001

  # when train atdh
  # 0.01
  # 300 [300] 'asgd' 'MultiStepLR' lr:0.01 display_eval: 199 (first time)
  # 2000 [500, 1000, 1500, 2000]      'adagrad' 'MultiStepLR' lr:0.00005 0.0001 0.0005 0.001