Models:
  name: RetinaNet
Backbones:
  name: resnet
  depth: 50
Head:
  name: baseline # senet, sknet, atdh, baseline
Data:
  name: myfire_trainval
  root: '/data/FireDataset'
  size: 608
Optimize:
  epoch: 50
  display_iter: 100
  display_eval: 4
  lr: 0.001
  optim: 'adagrad'
  batch_size: 8
  scheduler: 'MultiStepLR'
  lr_step: [300, 600]
  warmup_steps: 1
  step: 200
  gamma: 0.5

  # resume RetinaNet_resnet50_minimyfire608_baseline_best_8781.pth
  # 0.001
  # 700 [ 200, 400, 500 ]  'adam' 'MultiStepLR' lr:0.001

  # when train atdh
  # 'adagrad' 'MultiStepLR' lr:0.001
  # 700 [ 300, 600, 700 ]