Models:
  name: RetinaNet
Backbones:
  name: resnet
  depth: 50
Data:
  name: test
  root: '/data/test'
  size: 360
Optimize:
  epoch: 800
  display_iter: 100
  display_eval: 49
  lr: 0.1
  optim: 'sgd'
  batch_size: 8
  scheduler: 'MultiStepLR'
  lr_step: [ 240, 300 ]
  warmup_steps: 1
  step: 200
  gamma: 0.5

  #  0.1   0.01
  # 300 [ 340, 300 ] 'sgd' 'MultiStepLR' lr:0.1
  # 0.001
  # 300 [ 300 ]  'adam' 'MultiStepLR' lr:0.001