Models:
  name: MyFireNet_FCOS
  pretrained: False
  freeze_bn: True
  freeze_stage_1: True
Backbones:
  name: resnet
  depth: 50
Neck:
  use_p5: True
  fpn_out_channels: 256
Head:
  name: sknet # atdh, sknet,senet,baseline
  use_GN_head: True
  cnt_on_reg: True
  prior: 0.01
Training:
  strides: [ 8, 16, 32, 64, 128 ]
  limit_range: [ [ -1,64 ],[ 64,128 ],[ 128,256 ],[ 256,512 ],[ 512,999999 ] ]
Inference:
  score_threshold: 0.05
  nms_iou_threshold: 0.6
  max_detection_boxes_num: 1000
Loss:
  add_centerness: True
Data:
  name: minimyfire
  root: '/data/FireDataset'
  size: [ 400, 666 ]
  class_num: 2
Optimize:
  epoch: 900
  display_iter: 100
  display_eval: 4
  lr: 0.0001
  optim: 'adagrad'
  batch_size: 8
  scheduler: 'MultiStepLR'
  lr_step: [300, 600]
  warmup_steps: 1
  step: 200
  gamma: 0.1

  #  0.1   0.01
  # 600 [ 300, 600 ] 'sgd' 'MultiStepLR' lr:0.1
  # 0.001
  # 700 [ 300, 600, 700 ]  'adam' 'MultiStepLR' lr:0.001

 # with sknet
  # 0.001      0.0005
  # 600 [ 300, 600 ] 'sgd' 'MultiStepLR' lr:0.001
  # 0.001
  # 900 [ 300, 600, 900 ]  'asgd' 'MultiStepLR' lr:0.001
