Models:
  name: MyFireNet_FCOS
  pretrained: False
  freeze_bn: True
  freeze_stage_1: True
Backbones:
  name: resnet
  depth: 50
Neck:
  use_p5: True
  fpn_out_channels: 256
Head:
  use_GN_head: True
  cnt_on_reg: True
  prior: 0.01
Training:
  strides: [ 8, 16, 32, 64, 128 ]
  limit_range: [ [ -1,64 ],[ 64,128 ],[ 128,256 ],[ 256,512 ],[ 512,999999 ] ]
Inference:
  score_threshold: 0.05
  nms_iou_threshold: 0.6
  max_detection_boxes_num: 1000
Loss:
  add_centerness: True
Data:
  name: VOC
  root: '/data/VOCdevkit/VOC2007'
  size: [ 400, 666 ]  # 416: [400,666], 832: [800, 1333]
  class_num: 20
Optimize:
  epoch: 100
  display_iter: 100
  display_eval: 79
  lr: 0.1
  optim: 'sgd'
  batch_size: 8
  scheduler: 'MultiStepLR'
  lr_step: [ 40, 60 ]
  warmup_steps: 1
  step: 200
  gamma: 0.1
  #  0.1   0.01
  # 100 [ 40, 60 ] 'sgd' 'MultiStepLR' lr:0.1
  # 0.001
  # 100 [ 100 ]  'adam' 'MultiStepLR' lr:0.001




